language: python

python:
  - "2.7"

before_script:
  - "pip install -r requirements.txt"
  - "make run-background"  # run gunicorn server
  - sleep 5  # # give Web server some time to bind to sockets, etc

script: make test-api

after_script:
  - "pkill gunicorn"

notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
